<?php
/**
 * Solvingmagento_OneStepCheckout login step template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Magento Core Team <core@magentocommerce.com>
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com), 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<div class="onestep-step">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <h3><?php if ($this->getQuote()->isAllowedGuestCheckout()) : ?>
            <?php echo $this->__('Checkout as a Guest or Register') ?>
        <?php else: ?><?php echo $this->__('Register to Create an Account') ?>
        <?php endif; ?></h3>
    <?php if ($this->getQuote()->isAllowedGuestCheckout()) : ?>
        <ul class="form-list">
            <?php if ($this->getQuote()->isAllowedGuestCheckout()) : ?>
                <li class="control">
                    <input
                        type="radio"
                        name="checkout_method"
                        id="login:guest" value="guest"
                        <?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_GUEST) : ?>
                            checked="checked"
                        <?php endif; ?>
                        class="radio" />
                    <label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                    </li>
            <?php endif; ?>
            <li class="control">
                <input
                    type="radio"
                    name="checkout_method"
                    id="login:register"
                    value="register"
                    <?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER
                        || !$this->getQuote()->isAllowedGuestCheckout()) : ?>
                        checked="checked"
                    <?php endif ?>
                    class="radio" />
                <label for="login:register"><?php echo $this->__('Register') ?></label>
            </li>
        </ul>
    <?php else: ?>
        <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
    <?php endif; ?>

    <h3><?php echo $this->__('Login') ?></h3>
    <p></p><?php echo $this->__('Already registered?') ?>
    <a href="/customer/account/login"><?php echo $this->__('Please log in') ?></a></p>
</div>
