<?php
/**
 * Solvingmagento_OneStepCheckout main template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<style>
    div.osc {
        padding: 5px;

        column-count: 3;
        column-gap: 20px;
        -moz-column-count: 3;
        -moz-column-gap: 20px;
        -webkit-column-count: 3;
        -webkit-column-gap: 20px;
    }
    div.section {

    }
    div.section h2 {
        float: left;
    }
    div.section .step-title {
        font-weight: bold;
        font-size: 16px;
        margin: 0 0 10px 0;
    }
</style>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/solvignmagento/onestepcheckout/Onestep.js') ?>"
    ></script>
<div class="osc" id="checkoutSteps" >
    <?php
    $i = 0;
    foreach ($this->getSteps() as $stepId => $stepInfo): ?>
        <?php if (!$this->getChild($stepId) || !$this->getChild($stepId)->isShow()): continue; endif; $i++ ?>
        <div id="osc-<?php echo $stepId ?>" class="section<?php echo !empty($stepInfo['complete'])?' saved':'' ?>">
            <div id="checkout-step-<?php echo $stepId ?>" class="step a-item">
                <div class="step-title">
                    <span class="number"><?php echo $i ?></span>
                    <span class="step-title"><?php echo $stepInfo['label'] ?></span>
                </div>
                <?php echo $this->getChildHtml($stepId) ?>
            </div>
        </div>
    <?php endforeach ?>
</div>
<script type="text/javascript">
</script>
