<?php
/**
 * Solvingmagento_OneStepCheckout review step template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Magento Core Team <core@magentocommerce.com>
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com), 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<div class="order-review" id="checkout-review-load">
    <?php echo $this->getChildHtml('info') ?>
</div>
