<?php
/**
 * Solvingmagento_OneStepCheckout review step template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Magento Core Team <core@magentocommerce.com>
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com), 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<div id="review-please-wait" class="step-please-wait" style="display: none">
        <span class="please-wait">
            <img
                src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                alt="<?php echo $this->__('Saving data, please wait...') ?>"
                title="<?php echo $this->__('Saving data, please wait...') ?>" class="v-middle" />
        </span>
</div>
<div style="clear: both">
    <a href="#_"  id="checkout-review-update"><?php echo Mage::helper('checkout')->__('Update order review');?></a>
</div>
<div class="order-review" id="checkout-load-review">
    <?php echo $this->getChildHtml('info') ?>
</div>
