<?php
/**
 * Solvingmagento_OneStepCheckout shipping method step template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Magento Core Team <core@magentocommerce.com>
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com), 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
        <img
            src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
            alt="<?php echo $this->__('Loading next step...') ?>"
            title="<?php echo $this->__('Loading next step...') ?>"
            class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</form>